/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package noname;

import Socket.Client;
import java.net.DatagramSocket;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.json.JSONObject;

/**
 *
 * @author phatv
 */
public class Dashboard extends javax.swing.JFrame {

    Client client = new Client();

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();

        new Thread(() -> {
            SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
            while (true) {
                try {
                    JSONObject jsonObj = new JSONObject();
                    jsonObj.put("action", "sensor");
                    jsonObj.put("actionId", 0);
                    String res = client.UDPSend(jsonObj.toString());
                    jsonObj = new JSONObject(res);
                    if (!jsonObj.isNull("success")) {
                        if (jsonObj.getBoolean("success")) {
                            JSONObject jsonTemp = jsonObj.getJSONObject("data");
                            String humidity = String.valueOf(jsonTemp.getJSONObject("humidity").get("value")) + " %";
                            String temperature = String.valueOf(jsonTemp.getJSONObject("temperature").get("value")).substring(0, 2) + " °C";
                            String heat_index = String.valueOf(jsonTemp.getJSONObject("heat_index").get("value")).substring(0, 2) + " °F";

                            txtHumidity.setText(humidity);
                            txtTemperature.setText(temperature);
                            txtHeatIndex.setText(heat_index);
                            txtLastUpdated.setText("Lần cập nhật cuối: " + formatter.format(new Date()));
                        }
                    }
                    Thread.sleep(3000);
                } catch (InterruptedException ex) {
//                    Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtHumidity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTemperature = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtHeatIndex = new javax.swing.JTextField();
        txtLastUpdated = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnLightingControl = new javax.swing.JMenuItem();
        btnScanLAN = new javax.swing.JMenuItem();
        btnFileStorage = new javax.swing.JMenuItem();
        btnExit = new javax.swing.JMenuItem();
        btnHelp = new javax.swing.JMenu();
        btnAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("By NoName @ 2022");

        jLabel2.setText("Độ ẩm:");

        txtHumidity.setEditable(false);

        jLabel3.setText("Nhiệt độ:");

        txtTemperature.setEditable(false);

        jLabel4.setText("Chỉ số nóng bức:");

        txtHeatIndex.setEditable(false);

        txtLastUpdated.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        txtLastUpdated.setText("Lần cập nhật cuối:");

        jMenu1.setText("Menu");

        btnLightingControl.setText("Lightning Control");
        btnLightingControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLightingControlActionPerformed(evt);
            }
        });
        jMenu1.add(btnLightingControl);

        btnScanLAN.setText("Scan IP/device in LAN");
        btnScanLAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScanLANActionPerformed(evt);
            }
        });
        jMenu1.add(btnScanLAN);

        btnFileStorage.setText("File Storage");
        btnFileStorage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFileStorageActionPerformed(evt);
            }
        });
        jMenu1.add(btnFileStorage);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jMenu1.add(btnExit);

        jMenuBar1.add(jMenu1);

        btnHelp.setText("Help");

        btnAbout.setText("About");
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });
        btnHelp.add(btnAbout);

        jMenuBar1.add(btnHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLastUpdated, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtHumidity, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtHeatIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHumidity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtHeatIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtLastUpdated)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnScanLANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScanLANActionPerformed
        ScanLAN frmSL = new ScanLAN();
//        frmSL.setLocationRelativeTo(null);
        frmSL.setVisible(true);
    }//GEN-LAST:event_btnScanLANActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        JOptionPane.showMessageDialog(null, "Một chiếc đồ án được thực hiện bởi nhóm NoName@2022.", "About", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAboutActionPerformed

    private void btnLightingControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLightingControlActionPerformed
        LightingControl frmLC = new LightingControl();
        frmLC.setLocationRelativeTo(null);
        frmLC.setVisible(true);
    }//GEN-LAST:event_btnLightingControlActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnFileStorageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFileStorageActionPerformed
        FileStorage frmFS = new FileStorage();
        frmFS.setVisible(true);
    }//GEN-LAST:event_btnFileStorageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnAbout;
    private javax.swing.JMenuItem btnExit;
    private javax.swing.JMenuItem btnFileStorage;
    private javax.swing.JMenu btnHelp;
    private javax.swing.JMenuItem btnLightingControl;
    private javax.swing.JMenuItem btnScanLAN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField txtHeatIndex;
    private javax.swing.JTextField txtHumidity;
    private javax.swing.JLabel txtLastUpdated;
    private javax.swing.JTextField txtTemperature;
    // End of variables declaration//GEN-END:variables
}
