/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package noname;

import Socket.Client;
import java.awt.Color;
import org.json.JSONObject;

/**
 *
 * @author phatv
 */
public class LightingControl extends javax.swing.JFrame {

    private Client client = new Client();
    private Color color;
    private int redValue = 0, greenValue = 0, blueValue = 0;

    /**
     * Creates new form LightingControl
     */
    public LightingControl() {
        initComponents();

        getLedState();
        changeColor();
        getColor();
    }

    private void getLedState() {
        JSONObject jsonObj = new JSONObject();
        jsonObj.put("action", "get-led-state");
        jsonObj.put("actionId", 1);
        String res = client.TCPSend(jsonObj.toString());
        System.out.println("State: " + res);
        jsonObj = new JSONObject(res);
        if (!jsonObj.isNull("success")) {
            if (jsonObj.getBoolean("success")) {
                JSONObject jsonTemp = jsonObj.getJSONObject("data");
                txtStatusLed.setText(jsonTemp.getString("status"));
            }
        }
    }

    private void updateLedState() {
        JSONObject jsonObj = new JSONObject();
        jsonObj.put("action", "set-led-state");
        jsonObj.put("actionId", 2);
        String res = client.TCPSend(jsonObj.toString());
        System.out.println("State: " + res);
        jsonObj = new JSONObject(res);
        if (!jsonObj.isNull("success")) {
            if (jsonObj.getBoolean("success")) {
                JSONObject jsonTemp = jsonObj.getJSONObject("data");
                txtStatusLed.setText(jsonTemp.getString("status"));
            }
        }
    }

    private void getColor() {
        JSONObject jsonObj = new JSONObject();
        jsonObj.put("action", "get-led");
        jsonObj.put("actionId", 3);
        String res = client.TCPSend(jsonObj.toString());
        jsonObj = new JSONObject(res);
        if (!jsonObj.isNull("success")) {
            if (jsonObj.getBoolean("success")) {
                JSONObject jsonTemp = jsonObj.getJSONObject("data");
                changeColor(jsonTemp.getInt("R"), jsonTemp.getInt("G"), jsonTemp.getInt("B"));
            }
        }
    }

    private void updateColor() {
        JSONObject jsonObj = new JSONObject();
        jsonObj.put("action", "set-led");
        jsonObj.put("actionId", 4);
        jsonObj.put("R", slrR.getValue());
        jsonObj.put("G", slrG.getValue());
        jsonObj.put("B", slrB.getValue());
        client.TCPSend(jsonObj.toString());
    }

    private void changeColor() {
        redValue = slrR.getValue();
        greenValue = slrG.getValue();
        blueValue = slrB.getValue();
        color = new Color(redValue, greenValue, blueValue);
        panColor.setBackground(color);
    }

    private void changeColor(int r, int g, int b) {
        redValue = r;
        slrR.setValue(r);
        greenValue = g;
        slrG.setValue(g);
        blueValue = b;
        slrB.setValue(b);
        color = new Color(redValue, greenValue, blueValue);
        panColor.setBackground(color);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSwitch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtStatusLed = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        slrR = new javax.swing.JSlider();
        slrG = new javax.swing.JSlider();
        slrB = new javax.swing.JSlider();
        btnUpdateLED = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        panColor = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        btnSwitch.setText("Bật / Tắt");
        btnSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSwitchActionPerformed(evt);
            }
        });

        jLabel1.setText("Trạng thái đèn:");

        txtStatusLed.setEditable(false);

        jLabel2.setText("Tín hiệu màu:");

        jLabel3.setText("RED:");

        jLabel4.setText("GREEN:");

        jLabel5.setText("BLUE:");

        slrR.setMaximum(255);
        slrR.setValue(100);
        slrR.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                changeColor(evt);
            }
        });

        slrG.setMaximum(255);
        slrG.setValue(100);
        slrG.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                changeColor(evt);
            }
        });

        slrB.setMaximum(255);
        slrB.setValue(100);
        slrB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                changeColor(evt);
            }
        });

        btnUpdateLED.setText("Cập nhật màu");
        btnUpdateLED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateLEDActionPerformed(evt);
            }
        });

        btnExit.setText("Thoát");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panColorLayout = new javax.swing.GroupLayout(panColor);
        panColor.setLayout(panColorLayout);
        panColorLayout.setHorizontalGroup(
            panColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panColorLayout.setVerticalGroup(
            panColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jLabel6.setText("Xem trước:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSwitch)
                        .addGap(82, 82, 82)
                        .addComponent(btnUpdateLED)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExit))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStatusLed)
                            .addComponent(slrR, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                            .addComponent(slrG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(slrB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtStatusLed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addComponent(slrR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(slrG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(slrB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSwitch)
                    .addComponent(btnUpdateLED)
                    .addComponent(btnExit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnUpdateLEDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateLEDActionPerformed
        changeColor();
        updateColor();
    }//GEN-LAST:event_btnUpdateLEDActionPerformed

    private void changeColor(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_changeColor
        changeColor();
    }//GEN-LAST:event_changeColor

    private void btnSwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSwitchActionPerformed
        updateLedState();
//        getLedState();
    }//GEN-LAST:event_btnSwitchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LightingControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LightingControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LightingControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LightingControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LightingControl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSwitch;
    private javax.swing.JButton btnUpdateLED;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel panColor;
    private javax.swing.JSlider slrB;
    private javax.swing.JSlider slrG;
    private javax.swing.JSlider slrR;
    private javax.swing.JTextField txtStatusLed;
    // End of variables declaration//GEN-END:variables
}
